### ISSUE TITLE
Unable to find image 'octoprint/youtubelive:latest' locally

### ISSUE THREAD

**Issue by Bigwerth** [jneilliii/OctoPrint-YouTubeLive#12]
Unable to find image 'octoprint/youtubelive:latest' locally
docker: Error response from daemon: pull access denied for octoprint/youtubelive, repository does not exist or may require 'docker login'.
See 'docker run --help'.

Don't know the docker user name and password, wasn't asked in the installation.

**Comment by jneilliii** [comment]
You missed a few steps in the instructions. That docker image is built locally after cloning a git.

**Comment by Bigwerth** [comment]
I followed the instruction:
Install docker

curl -sSL https://get.docker.com | sh
sudo usermod pi -aG docker
sudo reboot

Pull Docker Image

docker pull alexellis2/streaming:17-5-2017

Clone Repository and Rebuild

cd ~
git clone https://github.com/jneilliii/youtubelive --depth 1
cd youtubelive
docker build -t octoprint/youtubelive

What do I miss?

**Comment by jneilliii** [comment]
In this part

cd youtubelive
docker build -t octoprint/youtubelive

Make sure you run the sucker build command with a space followed by a period. Like this...

cd youtubelive
docker build -t octoprint/youtubelive .

**Comment by jneilliii** [comment]
Once you build you can run the test command I  the instructions and verify it's working.
