### ISSUE TITLE
Getting a Connection aborted error message.

### ISSUE THREAD

**Issue by geek3dgeek** [jneilliii/OctoPrint-YouTubeLive#13]
('Connection aborted.', error(2, 'No such file or directory'))

Any thoughts?

The plug in does see the youtube channel, I see the default logo on the video, but when I press Go Live, I get the error message.

**Comment by jneilliii** [comment]
Did you follow the instructions on creating the docker image, etc. Also make sure to update the webcam stream url to be fully qualified url with the ip address.

**Comment by geek3dgeek** [comment]
Nope. Guess RTFM'ing is still a thing. ;-) Thanks.

**Comment by geek3dgeek** [comment]
Just following up, your instructions were perfect. Thanks again. Very cool.
