### ISSUE TITLE
Getting this error when trying to pull

### ISSUE THREAD

**Issue by JesseBlan** [jneilliii/OctoPrint-YouTubeLive#14]
failed to register layer: Error processing tar file(exit status 1): unexpected EOF

**Comment by jneilliii** [comment]
Where are you getting that, after what command?

**Comment by JesseBlan** [comment]
docker pull alexellis2/streaming:17-5-2017

**Comment by jneilliii** [comment]
That's odd, I've ran this on a couple of octopi installs and never ran into that error.

**Comment by JesseBlan** [comment]
I havent either...but this is the first time Ive attempted it
