### ISSUE TITLE
no tab and config after enable from 1.37rc4

### ISSUE THREAD

**Issue by fred2088** [jneilliii/OctoPrint-YouTubeLive#19]
no tab and config page after enable from plugin manager on 1.37rc4

**Comment by jneilliii** [comment]
Thanks, I'll test that on my end and see what's going on.

**Comment by jneilliii** [comment]
I've tested on my RC4 installation and am not having any issues as you described.  I uninstalled, deleted the previous settings and installed from the plugin manager as if it was a brand new installation.

Are there any errors in your octoprint.log or browser's debug console?

**Comment by fred2088** [comment]
tried on Pi3 and Pi zero work fine, but not from Windows while it install successfully ...

**Comment by jneilliii** [comment]
That makes sense, I only use Pis.  Based on the error though, it looks like you may be able to install pypiwin32 maybe?

**Comment by fred2088** [comment]
still can't get it work after installed pypiwin32 ?

**Comment by fred2088** [comment]
yes
