### ISSUE TITLE
Issues starting docker

### ISSUE THREAD

**Issue by timolow** [jneilliii/OctoPrint-YouTubeLive#2]
Can you please provide detail as what to fill in for these values?  xxxx-xxxx-xxxx-xxxx  It doesnt seem to match youtube ID as needed in settings.

Thanks,

Tim

**Comment by jneilliii** [comment]
In plugin settings you use your youtube channel id.  Follow the link [here](https://support.google.com/youtube/answer/3250431?hl=en) to determine how to get that.

For the docker command you need to take a look at Step 4 in the instructions over [here](https://blog.alexellis.io/live-stream-with-docker/).

**Comment by scns** [comment]
Duplicate of #5
