### ISSUE TITLE
youtube live error ?

### ISSUE THREAD

**Issue by fred2088** [jneilliii/OctoPrint-YouTubeLive#21]
('Connection aborted.', error(2, 'No such file or directory'))

**Comment by jneilliii** [comment]
Did you follow the instructions to set up?

**Comment by fred2088** [comment]
enter YouTube Channel ID and YouTube Stream ID
got my youtube screen from youtubelive tab

**Comment by jneilliii** [comment]
There's a lot more necessary to get this to work. Read the [instructions](https://github.com/jneilliii/OctoPrint-YouTubeLive/blob/master/docker_instructions.md).
