### ISSUE TITLE
YouTube Live Error ('Connection aborted.', error(2, 'No such file or directory'))

### ISSUE THREAD

**Issue by slablanc42** [jneilliii/OctoPrint-YouTubeLive#23]
I've installed the plugin and have put in my Channel ID and what I believe is my Stream ID, when I click Go Live I'm getting the error message above.

Do I still need to install docker? I'm very much a newbie when it comes to working in shell commands, I downloaded Putty but would prefer to not use it unless necessary.  

Also, at the very bottom of your instructions you mention "changing your webcam stream url to a fully qualified URL using ip address of your pi", how do I find the IP address of my PI?

**Comment by jneilliii** [comment]
Yes, you need to follow those instructions to get the plugin fully functional. Once you ssh to your pi, it's pretty much a copy/paste operation from the instructions. To get the ip of your pi you can type ifconfig in the putty console once connected. Be aware, that the IP can change, based on your router's configuration.
