### ISSUE TITLE
YouTube Live Error 409

### ISSUE THREAD

**Issue by slablanc42** [jneilliii/OctoPrint-YouTubeLive#24]
I've installed the plugin (put in client and stream IDs), used Putty to copy and paste the docker, etc..., changed my Webcam from localhost:8080 to 192.168... and I'm getting this message when I click on the go live button. 

409 Client Error: Conflict ("Conflict. The container name "/YouTubeLive" is already in use by container "5fded366f754a80006e88dd2e30f8a1cd79b086516ea4d30d5e9e4fab023c15c". You have to remove (or rename) that container to be able to reuse that name.")

When I run the test line in Putty I get this message:

docker: Error response from daemon: Conflict. The container name "/YouTubeLive" is already in use by container "5fded366f754a80006e88dd2e30f8a1cd79b086516ea4d30d5e9e4fab023c15c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Any suggestions would be appreciated.

Edit: I ran through the instructions again from Pull Docker Image down to test. Now when I click on the Go Live button it just hangs there, the stream says offline and the Go Live button looks like it's been pressed and a wheel is just going in a circle like it's thinking. When I run the test in docker I get: 

docker: Error response from daemon: Conflict. The container name "/YouTubeLive" is already in use by container "97ddf05a3dab76d784a3434e7185ced4972d65f38cf5094866b32247b99d47fd". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by jneilliii** [comment]
That error is typically caused by the testing procedure not being cancelled after testing is complete.  In the [instructions](https://github.com/jneilliii/OctoPrint-YouTubeLive/blob/master/docker_instructions.md) under the Test section...

```
ctrl+c
docker rm YouTubeLive
```
