### ISSUE TITLE
Channel ID is the User ID, Stream ID is the Stream name/key

### ISSUE THREAD

**Issue by Budavaril** [jneilliii/OctoPrint-YouTubeLive#25]
I followed the instructions and did exactly everithyng, but spent a day to find out why not working to me.

**Homepage says:**
"....enter your YouTube's channel id..."

**In the WEBGUI:**
"**YouTube Channel ID**:  enter your personal **channel id** here"

**Howto says:**
"OctoPrint Settings
- Enter your **stream id** used above in the OctoPrint-YouTubeLive plugin settings.
- _Change your webcam stream url to a fully quliafied url using the ip address of your pi like http://192.168.1.2:8080/?action=stream" ( I think is not totally clear for everyone this should be to do in the "OctoPrint Settings -> Webcam & Timelapse )_

So that "Channel ID" everywhere definied wrong. 
There should be write **"YouTube User ID"** and not the"YouTube Channel ID"   
That can find at same place "Account-> Advanced Settings, but just above the Channel ID. 
After a day I realized I'm finally able to see my stream in the WEBGUI.  

![youtube id](https://user-images.githubusercontent.com/19350571/39861220-d0b49c2c-5437-11e8-9383-b73a141f50bf.PNG)

**Comment by jneilliii** [comment]
Not sure why the Channel ID is not working for you like it does for me.  Your View of the YouTube Advanced Settings does look a little different than mine though, as it's themed in black, and maybe it's because you have a brand account set-up and I don't?
