### ISSUE TITLE
Music & print status

### ISSUE THREAD

**Issue by majda107** [jneilliii/OctoPrint-YouTubeLive#26]
Hi,

could you suggest me idea, how could I add progress bar of printing process, image of model or music into my stream?

Thanks!

Sincerely,
Marián Trpkoš.

**Comment by jneilliii** [comment]
Modifying the entry.sh file to input an mp3 or wav file as audio source should in theory work to add audio.  Edit the line in the file that was cloned from [here](https://github.com/jneilliii/youtubelive/blob/a8f248a42c3c3fa5264226d551f0efc72b761d56/entry.sh#L7) replacing `-i /dev/zero -acodec aac -ab 128k` with something like `-i /path/filename.mp3 -acodec aac -ab 128k`.

Adding the print progress as an overlay would take a considerable amount of work to achieve for the plugin, but could be accomplished modifying the same entry.sh file to also include a watermark image.  See [here](http://ksloan.net/watermarking-videos-from-the-command-line-using-ffmpeg-filters/) for an example.  The hard part here is that I don't know if you replace the image while streaming if it would reload the image while encoding/streaming to YouTube.
