### ISSUE TITLE
('Connection aborted.', error(2, 'No such file or directory'))

### ISSUE THREAD

**Issue by reederda** [jneilliii/OctoPrint-YouTubeLive#30]
I installed this plugin from Octoprint's plugin manager. I followed the instructions regarding the channel and stream ids, but when I try to "go live" I get the following error:
('Connection aborted.', error(2, 'No such file or directory'))

**Comment by jneilliii** [comment]
Did you change your webcam stream url to include the IP address?

**Comment by reederda** [comment]
I have done that, yes.

**Comment by jneilliii** [comment]
Can you please upload your octoprint.log file or look for any errors in that file related to the plugin? Some have said that they had to restart octoprint after setting the webcam stream url to include the IP for it to take effect.

**Comment by reederda** [comment]
Upon further inspection, it appears that the docker container did not build successfully. I'm trying to now, however, and am receiving the error:

standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c chmod +x entry.sh' returned a non-zero code: 1

**Comment by gretel** [comment]
i get that exact same error now - as i re-installed this plugin.

**Comment by jneilliii** [comment]
@gretel, did you start from scratch with the setup instructions, or just reinstall the plugin part inside OctoPrint? It was working before and now it doesn't? Is the test command successful from the instructions?

**Comment by gretel** [comment]
@jneilliii no, yes, yes, yes. 😁

**Comment by jneilliii** [comment]
That is odd. Anything else change outside of uninstalling the plugin and reinstalling? Does the webcam url in OctoPrint settings still have the ip address included?

**Comment by gretel** [comment]
i had to postpone further investigation but are trying to get back, soon.

**Comment by otherguy** [comment]
Any updates? I have the same issue. Fresh OctoPi/OctoPrint install.

**Comment by jneilliii** [comment]
@otherguy, did you follow the prerequisite instructions found [here](https://github.com/jneilliii/OctoPrint-YouTubeLive/blob/master/docker_instructions.md)?

**Comment by otherguy** [comment]
@jneilliii I did but it was quite late (or early in the morning) 😉  I'm well versed with Docker and I'll look into it on the weekend.

**Comment by jneilliii** [comment]
I know near nothing about docker, so you're in better shape than myself. I just hacked this together the best I could. The one thing that is the most common issue is changing octoprint's webcam and timelapse setting to be a full url with IP because relative pathing won't be interpreted correctly by the docker image. Make sure to restart octoprint after making that change as well.

**Comment by pstimpel** [comment]
I have the same error. fresh octoprint install, up to date, installed the plugin. I was verifying my youtube settings using obs, working. I made sure using the FQDN for the stream cam. I restarted both octoprint and the RPI. I receive the same error over and over.

I was trying those for the camera

http://myip/webcam/?action=stream

http://myip:8080/?action=stream

Both URLs show the stream of my camera, however, livestreaming failes with the message from the subject.

octoprint.log 


2019-01-03 21:13:59,771 - octoprint.plugins.youtubelive - INFO - OctoPrint-YouTubeLive loaded! Checking stream status.                                                              

2019-01-03 21:13:59,781 - octoprint.plugins.youtubelive - ERROR - ('Connection aborted.', error(2, 'No such file or directory'))

Any idea?

**Comment by jneilliii** [comment]
@pstimpel; did you follow the instructions linked in the [requirements for streaming](https://github.com/jneilliii/OctoPrint-YouTubeLive#requirements-for-streaming) section? Seems like you don't have docker image set-up...you can't just install the plugin there are other steps...

**Comment by hevilp** [comment]
Do you can change the plugin to use an existing mjpg_streamer and not the docker image?

**Comment by jneilliii** [comment]
The docker image re-encodes the existing mjpegstream to the appropriate format and pushes it to YouTube.
