### ISSUE TITLE
Could This Work For Twitch

### ISSUE THREAD

**Issue by BeerGeekGamer** [jneilliii/OctoPrint-YouTubeLive#32]
Hello,

I was wondering if you have any insight if this could work with Twitch. I read the blog article which the work is based on, and even though I do have some programming skills, I will admit this is a little more advance then the skills I possess. I am not familiar with Docker, but could you edit alexellis2 image to point to the Twitch rtmp location instead of YouTube's?

**Comment by jneilliii** [comment]
Assuming twitch uses a similar rtmp url to post to I would think it would work just changing the url in the entry.sh file would do the trick. I'll see about creating a twitch account and test for you.

**Comment by BeerGeekGamer** [comment]
That would be awesome!

I have figured out a little work around, by installing libav-tools and using the following command:

`raspivid -t 0 -fps 25 -hf -b 2000000 -o - | avconv -i - -vcodec copy -an -r 30 -g 30 -bufsize 2000000 -pix_fmt yuv420p -f flv rtmp://TWITCH_INGEST_ENDPOINT/YOUR_STREAM_KEY_HERE`

The only thing is, you have to kill the mjpg_streamer process for this to work, or you'll get `mmal_vc_component_enable failed to enable component enospc` since mjpg-streamer is started at boot and is using the camera. I was just hoping you could do this with mjpg-streamer since it's already installed through Octopi and then I wouldn't have to install anything else.

**Comment by jneilliii** [comment]
I'll probably end up forking this plugin to a new one in order to have the right view tab, as that would definitely not work. Do you happen to know if twitch is like youtube and has a direct url to view a specific user's stream?

**Comment by BeerGeekGamer** [comment]
Yes, for Twtich you can use this site ([https://stream.twitch.tv/ingests/](url)) to find the recommended Twitch rtmp endpoints, based on the optimal network paths from your device. Then from your Twitch channel you grab our Stream Key and just append it to the end.

So for example: rtmp://live-dfw.twitch.tv/app/YOUR_TWITCH_KEY_HERE

**Comment by jneilliii** [comment]
![image](https://user-images.githubusercontent.com/5249455/43938861-2071d54c-9c34-11e8-9b90-0fb32f971b92.png)

**Comment by BeerGeekGamer** [comment]
Awesome, thank you so much. I don't know if I'll have time to test it out
today, but I'll definitely let you know once I get it up and running.
