### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by K34nu** [jneilliii/OctoPrint-YouTubeLive#35]
Hi Jneilliii,

Can I grab a copy of the dockerfile please? I'm hoping to make it a bit smaller and fix the issue with it not working on my system. (Non-Pi system)

Thanks,
-K34nu

**Comment by jneilliii** [comment]
It's on github, but probably not much there for you to change, you're probably looking for the one from alexellis2 instead, add mine just references his. 

Mine: 
 https://github.com/jneilliii/youtubelive

**Comment by K34nu** [comment]
Got'cha, asked in the wrong place! Thanks for the heads up 👍
