### ISSUE TITLE
Sream URL in youtube live different from the stream url in octoprint  web cam settings

### ISSUE THREAD

**Issue by eshmaya** [jneilliii/OctoPrint-YouTubeLive#42]
Hello,

In some cases there is a need to put different stream URL in youtube live from the url in octoprint webcam settings.

Adding the possiblity to put specific url in youtube live settings will be appriciated.

Best Regards,
Eli

**Comment by jneilliii** [comment]
For a more generic option you should look at my other plugin rtmpstreamer, which allows for that.
