### ISSUE TITLE
Should this to work with an Ubuntu install of Octoprint?

### ISSUE THREAD

**Issue by Jabberie** [jneilliii/OctoPrint-YouTubeLive#43]
I'm waiting on my RPi to arrive and was trying out an old laptop I have in the meantime. 

Anything I can do with this?

![image](https://user-images.githubusercontent.com/18558639/50542046-61859100-0baa-11e9-991f-8c5ceb85e913.png)

**Comment by jneilliii** [comment]
You may need to sudo the command for docker build so it has the necessary rights to make the sh file executable.

**Comment by Jabberie** [comment]
Tried it again, no joy.
