### ISSUE TITLE
Can't complete docker build on CentOS 7

### ISSUE THREAD

**Issue by Erik10206** [jneilliii/OctoPrint-YouTubeLive#45]
I am trying to get this youtube live plugin going but I keep getting this error when attempting the build:

$ docker build -t octoprint/youtubelive .
Sending build context to Docker daemon  53.25kB
Step 1/3 : FROM alexellis2/streaming:07-05-2018
 ---> a8d02138647f
Step 2/3 : COPY entry.sh entry.sh
 ---> Using cache
 ---> a1926c00157e
Step 3/3 : RUN chmod +x entry.sh
 ---> Running in 78a43fc1f3d1
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c chmod +x entry.sh' returned a non-zero code: 1

I am running octoprint on a Cent7 box that I built but I am not very familiar with docker. I have tried formatting the command in the Docker file but almost everything fails in the same error. Octoprint runs as a user called octoprint and when following the instructions for docker setup, I swapped the pi user for my octoprint user. It does not appear to be a permissions issue as root has the same error. Let me know if there are any other details you need. I am anxious to get this working.

**Comment by jneilliii** [comment]
This is the same issue as #43.  The docker image is based on a raspbian stretch build of ffmpeg done by someone else. I'm just importing it.  If you could find a centos specific version you could modify the docker file to account for the difference I think..
