### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by petitxef** [jneilliii/OctoPrint-YouTubeLive#46]
Hi! 
I followed the instructions and all fine on the prerequisites (I streamed by terminal)

But if I push the red  button “go live” at YouTube live tab, an error shows up:

YouTube Live Error
('Connection aborted.', error(13, 'Permission denied'))

I check twice the YouTube Channel ID and the stream ID. 

What I need to fix this problem?

Thanks in advance!

**Comment by jneilliii** [comment]
My best guess is the second line in the prerequisites. That's what gives the user permission to run docker. 

```
sudo usermod pi -aG docker
```

**Comment by petitxef** [comment]
Thanks jneiliii, but now show other problem:
YouTube Live Error
409 Client Error: Conflict ("Conflict. The container name "/YouTubeLive" is already in use by container "1e253235eef251fab483893870afd615a1e6b1e5e62800b1958c52e6219572e7". You have to remove (or rename) that container to be able to reuse that name.")

What’s better option, I’m not good with terminal.

**Comment by jneilliii** [comment]
Restart the pi and that should get you back to working from the plugin. Probably have a container running from when you ran the test command.

**Comment by jneilliii** [comment]
Maybe docker is making the image persistent.  If you connect SSH and run the following in terminal it might fix the issue.

```
docker rm YouTubeLive
```

**Comment by petitxef** [comment]
Thanks for the help, but still doesn’t work. 

If I run by terminal, works perfect (I can watch on YouTube) but if when I run on octoprint, does not work. 

Happen the same, when I open the YouTube live tab shows the button “stop” but on YouTube live dashboard shows offline. If I push stop and click again, the same error before.

Maybe I need erase all and start again?

**Comment by petitxef** [comment]
I have octolapse installed, but disable. Do you need some specific setting to share with you?

**Comment by jneilliii** [comment]
Not octolapse, the default webcam and timelapse settings section of octoprint settings.

**Comment by petitxef** [comment]
Here the settings
![imagen](https://user-images.githubusercontent.com/25556673/51752505-f69b7d00-20b7-11e9-91fd-bf5445c135df.png)
![imagen](https://user-images.githubusercontent.com/25556673/51752547-0b781080-20b8-11e9-8b9c-bc6f5162fc02.png)

**Comment by jneilliii** [comment]
Yep, change that first setting  'stream url' to the same thing you use in the test command and restart octoprint.

**Comment by petitxef** [comment]
To clarify, I need to put the next code on the stream url box:

docker run --privileged --name YouTubeLive -ti octoprint/youtubelive:latest http://<ip>:8080/?action=stream xxxx-xxxx-x (Changing obviously the ip of the raspberry and the live stream id)

It’s correct?

**Comment by jneilliii** [comment]
No just this part...

```
http://<ip>:8080/?action=stream
```

Like this...

![image](https://user-images.githubusercontent.com/5249455/51771683-d4a1fa80-20b7-11e9-8f0b-55274e1d5e2c.png)

**Comment by petitxef** [comment]
Ok, done, but when I start printing show again this error:

YouTube Live Error
409 Client Error: Conflict ("Conflict. The container name "/YouTubeLive" is already in use by container "8dad9d210a68e7d993887064f9666ed8cdbcc82d8a7b8609f7f334a84d529ea7". You have to remove (or rename) that container to be able to reuse that name."). 

Maybe is easier to erase everything and start fresh again :S

**Comment by jneilliii** [comment]
Connect back in to terminal and type 
```
docker rm YouTubeLive
```

**Comment by petitxef** [comment]
Nothing. Not working. I’ll try a fresh install. I don’t want you spends more time with this problem. Tomorrow morning I’ll install all octoprint again (isn’t a big deal)
