### ISSUE TITLE
 Avoid running the container in privileged mode

### ISSUE THREAD

**Issue by d6e** [jneilliii/OctoPrint-YouTubeLive#48]
Using Docker's `--privileged` option is a really bad idea unless absolutely necessary as it grants the container root access to the host. Instead, let's limit it to just what it needs. Docker run has an option for exactly this purpose: `--device=/dev/vchiq`.

**Comment by jneilliii** [comment]
Merged, will be testing the network_mode option a little more and then releasing.

**Comment by jneilliii** [comment]
Just release 0.5.1 which incorporates your changes.
