### ISSUE TITLE
Unknown flag: --network_mode

### ISSUE THREAD

**Issue by bigben4001** [jneilliii/OctoPrint-YouTubeLive#51]

**Comment by bigben4001** [comment]
Whenever I try to test run the stream I run:
docker run --device=/dev/vchiq --network_mode="host" --name YouTubeLive -ti octoprint/youtubelive:latest http://<ip>:8080/?action=stream xxxx-xxxx-xxxx-xxxx null
but with my stream id and my ip address. Every time I run it i get the following error:
unknown flag: --network_mode

**Comment by IntegersOfK** [comment]
Same problem here, but then I tried `--network="host"` and it worked.

**Comment by jneilliii** [comment]
Updated instructions.
