### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by ppetrov-dev** [jneilliii/OctoPrint-YouTubeLive#54]
I cannot connect to a stream. I have the following error
![error](https://user-images.githubusercontent.com/11585634/69662495-24ad6d00-108d-11ea-8f63-ce678602ec44.png)

**Comment by jneilliii** [comment]
I haven't worked on this plugin in quite sometime. I recommend the webcam streamer plugin instead.

**Comment by jneilliii** [comment]
But I suspect the issue is with the steam url in octoprint's timelapse and webcam settings not being a full url.
