### ISSUE TITLE
Help Wanted: Docker uninstall

### ISSUE THREAD

**Issue by ProfEngr** [jneilliii/OctoPrint-YouTubeLive#56]
Decided I'm not going to use the plugin and wanted to get the docker install off the Pi as well. What's the best way to handle that?

**Comment by jneilliii** [comment]
You'll need to remove the containers added I'm assuming first.

https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/

Then use `apt-get remove --purge docker` to uninstall docker.

**Comment by ProfEngr** [comment]
Thanks.
