### ISSUE TITLE
[Feature Request] Allow overriding the web cam URL

### ISSUE THREAD

**Issue by ManuelMcLure** [jneilliii/OctoPrint-YouTubeLive#57]
In some configurations (for example if OctoPrint is proxied to multiple independent networks) it is impossible to use an absolute URL in the OctoPrint webcam settings but instead a URL of the form
```
/webcam/?action=stream
```
must be used so the webcam works properly regardless of connectivity between the networks. This unfortunately breaks the OctoPrint-YouTubeLive plugin since it requires an absolute URL.

It would be nice if there was a way to override the webcam URL for the plugin.

**Comment by jneilliii** [comment]
The webcamstreamer plugin is probably for you based on this request.
