### ISSUE TITLE
Youtubelive plugin parameter

### ISSUE THREAD

**Issue by pierremilcent** [jneilliii/OctoPrint-YouTubeLive#62]
I installed the plugin and followed all configuration steps with success.

I was able to stream on youtube at the Test step.

I am blocked at the last one "OctoPrint Settings". 
![image](https://user-images.githubusercontent.com/38214885/95487205-4c9b7b80-0994-11eb-9898-8050e46164ab.png)

What is this "YouTube Channel ID" ?

Thanks for your help

**Comment by pierremilcent** [comment]
I found my channel ID in the advanced parameter section under Parameter in My Profile.
Here is what i get.

![image](https://user-images.githubusercontent.com/38214885/95489005-89687200-0996-11eb-812d-0ba495f1b46b.png)

So now how to get the video stream from the camera ?

**Comment by jneilliii** [comment]
Try following the instructions first. 

https://github.com/jneilliii/OctoPrint-YouTubeLive#requirements-for-streaming

**Comment by jneilliii** [comment]
After looking at you screenshot again from my computer rather than my phone, it looks like you're getting the stream started fine? Are you able to access it from your YouTube Live dashboard to see the stream status?

**Comment by pierremilcent** [comment]
Hello, 

no it does not work as expected. All steps with the test are OK, but when finishing and trying with the plugin it does not work. 
I am sot sure at all what are the channel id and stream id are. Here is what i used : 

























And when i STOP Live here the message i get 












May i reinstall from scratch ? 

Regards. Cordialement. 

Pierre Milcent 

Viméo: https://www.vimeo.com/milcent 
Blog: https://milcent.wordpress.com 
Youtube: http://www.youtube.com/pmilcent 

----- Mail original -----

De: "jneilliii" <notifications@github.com> 
À: "jneilliii/OctoPrint-YouTubeLive" <OctoPrint-YouTubeLive@noreply.github.com> 
Cc: "Pierre" <pierre.milcent@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 9 Octobre 2020 02:30:32 
Objet: Re: [jneilliii/OctoPrint-YouTubeLive] Youtubelive plugin parameter (#62) 





After looking at you screenshot again from my computer rather than my phone, it looks like you're getting the stream started fine? Are you able to access it from your YouTube Live dashboard to see the stream status?

**Comment by jneilliii** [comment]
If the test command worked, then the only thing that usually prevents the stream from working when you start it is changing the webcam and timelapse setting's stream URL to match the URL you used in the test command. The embedded viewer tab may be a problem related to embedding as I have been getting an error with mine for quite some time now and believe it to be some embed problem but haven't had the time to investigate further.
