### ISSUE TITLE
('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) 

### ISSUE THREAD

**Issue by Sausages69** [jneilliii/OctoPrint-YouTubeLive#74]
Hi there. Call me dumb or whatever, but I can't get this to work anymore. I guess youtube must've changed something again. 
Is it working for everyone else still?
My versions are Octroprint (on octopi) 1.9.2 and YT Live is 0.5.2

Thanks in advance
Sausage

**Comment by jneilliii** [comment]
will probably need more details. enable debug ffmpeg in the plugin's settings on the ffmpeg tab under advanced options. Restart OctoPrint fresh and then try to start stream. then share the octoprint.log and plugin_rtmpstreamer_engine.log from logging section of OctoPrint's settings.
