### ISSUE TITLE
Issue help plzz

### ISSUE THREAD

**Issue by codegenerator01** [jneilliii/OctoPrint-YouTubeLive#76]
Hello good stuff! But im getting this error: 

pi@octopi:~ $ docker run --device=/dev/vchiq --network="host" --name YouTubeLive -ti octoprint/youtubelive:latest http://**Incrypted**:8080/?action=stream **Incrypted** null
OctoPrint Webcam Stream: http://192.168.2.10:8080/?action=stream
Live-stream secret: **Incrypted**
Filter: null
ffmpeg version N-90990-g652b857b94 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
  libavutil      56. 18.100 / 56. 18.100
  libavcodec     58. 19.101 / 58. 19.101
  libavformat    58. 13.101 / 58. 13.101
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 21.100 /  7. 21.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[tcp @ 0x1df05a0] Connection to tcp://**Incrypted**:8080 failed: Connection refused
http://1**Incrypted**:8080/?action=stream: Connection refused

any way you could help?

**Incrypted** is the ip and streming key from youtube

**Comment by jneilliii** [comment]
I'd recommend trying the rtmpstreamer plugin instead of this one as it's been converted to not require docker and the additional complexity involved.
