### ISSUE TITLE
Possible to change to ip?

### ISSUE THREAD

**Issue by stayupthetree** [jneilliii/OctoPrint-YouTubeLive#8]
The only way I could get this to work was changing http://localhost:8080/?action=stream to use my local ip.

ie http://192.168.1.128:8080/?action=stream

So is there a way to change it within OctoPrint like I do the command line?

**Comment by jneilliii** [comment]
Perfect, in octoprint's settings use that url for the webcam stream in webcam settings and then enter your stream id in the YouTube live plugin settings and then restart octoprint. Should be good to go.
